### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by FediSalhi** [dan-42/spoon#1]
Is the project still active? Do you still review pull requests??

**Comment by dan-42** [comment]
Dear @FediSalhi, traveler of the internet :-)

I have not worked on this project for 5 years.
So I'm not even sure if this is still needed and it never left the prototyping stage.

So out of curiosity are you using this code?
And maybe there are better solutions now for what I once tried to write this.
Since I switched jobs this project became less interesting for me.


Back to your question: If you have a PR I will review it and merge it.

**Comment by FediSalhi** [comment]
Thank you for reply Dan. I often need (de)serializers for my communication protocols (for the payload part of the packets to be sent or received). I've written some in C language, in very simple way. But I will need C++ (de)serializers, with a better design. I will start working on them and it would be great if you can help with some review.

**Comment by dan-42** [comment]
Ok I see, so if it is only parsing, 
lexy (https://github.com/foonathan/lexy)  might be better for you.
Also there is documentation, examples, ...

**Comment by FediSalhi** [comment]
This is helpful Dan, thank you for your time

**Comment by dan-42** [comment]
No problem, so I close this issue.
Good luck on your project
